apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Customer-Cache
  description: Redis Server App
  tags:
    - nosql
    - redis
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=redis-server,tier=cache'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: CustomerRating-Team
  system: CustomerManagement
  dependsOn: [Component:yelb-db]
