apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Customer-Cache
  description: This is a caching component for the Customer rating system. This is a redis server cache which uses a LRU cache to store customer details as they are pulled out by the Customer rating engine.
  tags:
    - nosql
    - redis
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=redis-server,tier=cache'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: Cache
  lifecycle: experimental
  owner: CustomerRating-Team
  system: CustomerManagement
  dependsOn: [Component:CustomerRating-db]
